In [5]:
!pip install datasets

Defaulting to user installation because normal site-packages is not writeable
Collecting datasets
  Downloading datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Collecting filelock (from datasets)
  Downloading filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting numpy>=1.17 (from datasets)
  Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-23.0.1-cp314-cp314-win_amd64.whl.metadata (3.1 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets)
  Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting requests>=2.32.2 (from datasets)
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting httpx<1.0.0 (from datasets)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting tqdm>=4.66.3 (from datasets)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp314-cp314-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py314-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2026.2.0,>=2023.1.0 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<2.0,>=0.25.0 (from datasets)
  Downloading huggingface_hub-1.9.1-py3-none-any.whl.metadata (14 kB)
Collecting packaging (from datasets)
  Downloading packaging-26.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pyyaml>=5.1 (from datasets)
  Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.5-cp314-cp314-win_amd64.whl.metadata (8.4 kB)
Collecting anyio (from httpx<1.0.0->datasets)
  Downloading anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting certifi (from httpx<1.0.0->datasets)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1.0.0->datasets)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1.0.0->datasets)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0->datasets)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading hf_xet-1.4.3-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting typer (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting typing-extensions>=4.1.0 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp314-cp314-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp314-cp314-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.23.0-cp314-cp314-win_amd64.whl.metadata (82 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.32.2->datasets)
  Downloading charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.32.2->datasets)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting colorama (from tqdm>=4.66.3->datasets)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting python-dateutil>=2.8.2 (from pandas->datasets)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting tzdata (from pandas->datasets)
  Downloading tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->datasets)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting click>=8.2.1 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading click-8.3.2-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading datasets-4.8.4-py3-none-any.whl (526 kB)
   ---------------------------------------- 0.0/527.0 kB ? eta -:--:--
   ------------------- -------------------- 262.1/527.0 kB ? eta -:--:--
   ------------------- -------------------- 262.1/527.0 kB ? eta -:--:--
   ---------------------------------------- 527.0/527.0 kB 829.3 kB/s  0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Using cached fsspec-2026.2.0-py3-none-any.whl (202 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading huggingface_hub-1.9.1-py3-none-any.whl (637 kB)
   ---------------------------------------- 0.0/637.4 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/637.4 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/637.4 kB ? eta -:--:--
   ---------------------------------------- 637.4/637.4 kB 1.1 MB/s  0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.7 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/3.7 MB 1.3 MB/s eta 0:00:03
   -------- ------------------------------- 0.8/3.7 MB 1.5 MB/s eta 0:00:02
   ----------- ---------------------------- 1.0/3.7 MB 1.6 MB/s eta 0:00:02
   -------------- ------------------------- 1.3/3.7 MB 1.3 MB/s eta 0:00:02
   ----------------- ---------------------- 1.6/3.7 MB 1.4 MB/s eta 0:00:02
   ---------------------- ----------------- 2.1/3.7 MB 1.5 MB/s eta 0:00:02
   ------------------------- -------------- 2.4/3.7 MB 1.4 MB/s eta 0:00:01
   ------------------------- -------------- 2.4/3.7 MB 1.4 MB/s eta 0:00:01
   ---------------------------- ----------- 2.6/3.7 MB 1.3 MB/s eta 0:00:01
   ------------------------------- -------- 2.9/3.7 MB 1.3 MB/s eta 0:00:01
   ---------------------------------- ----- 3.1/3.7 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 3.4/3.7 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 3.7/3.7 MB 1.3 MB/s  0:00:02
Downloading multiprocess-0.70.19-py314-none-any.whl (160 kB)
Downloading aiohttp-3.13.5-cp314-cp314-win_amd64.whl (464 kB)
Downloading multidict-6.7.1-cp314-cp314-win_amd64.whl (45 kB)
Downloading yarl-1.23.0-cp314-cp314-win_amd64.whl (89 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Downloading frozenlist-1.8.0-cp314-cp314-win_amd64.whl (44 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 1.2 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.4 MB 1.2 MB/s eta 0:00:11
   ---- ----------------------------------- 1.3/12.4 MB 1.3 MB/s eta 0:00:09
   ----- ---------------------------------- 1.6/12.4 MB 1.4 MB/s eta 0:00:08
   ------ --------------------------------- 2.1/12.4 MB 1.5 MB/s eta 0:00:07
   ------- -------------------------------- 2.4/12.4 MB 1.5 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.4 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.4 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 3.1/12.4 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 3.4/12.4 MB 1.5 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.4 MB 1.5 MB/s eta 0:00:06
   ------------- -------------------------- 4.2/12.4 MB 1.5 MB/s eta 0:00:06
   -------------- ------------------------- 4.5/12.4 MB 1.5 MB/s eta 0:00:06
   ---------------- ----------------------- 5.0/12.4 MB 1.6 MB/s eta 0:00:05
   ---------------- ----------------------- 5.2/12.4 MB 1.6 MB/s eta 0:00:05
   ------------------ --------------------- 5.8/12.4 MB 1.6 MB/s eta 0:00:05
   -------------------- ------------------- 6.3/12.4 MB 1.6 MB/s eta 0:00:04
   --------------------- ------------------ 6.6/12.4 MB 1.6 MB/s eta 0:00:04
   --------------------- ------------------ 6.8/12.4 MB 1.6 MB/s eta 0:00:04
   ----------------------- ---------------- 7.3/12.4 MB 1.6 MB/s eta 0:00:04
   ------------------------- -------------- 7.9/12.4 MB 1.7 MB/s eta 0:00:03
   -------------------------- ------------- 8.1/12.4 MB 1.7 MB/s eta 0:00:03
   ---------------------------- ----------- 8.9/12.4 MB 1.7 MB/s eta 0:00:03
   ----------------------------- ---------- 9.2/12.4 MB 1.7 MB/s eta 0:00:02
   ------------------------------- -------- 9.7/12.4 MB 1.8 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.8 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.4 MB 1.8 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.4 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.4 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.4 MB 1.7 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.4 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 1.6 MB/s  0:00:07
Using cached packaging-26.0-py3-none-any.whl (74 kB)
Using cached propcache-0.4.1-cp314-cp314-win_amd64.whl (41 kB)
Downloading pyarrow-23.0.1-cp314-cp314-win_amd64.whl (28.2 MB)
   ---------------------------------------- 0.0/28.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/28.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/28.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/28.2 MB ? eta -:--:--
    --------------------------------------- 0.5/28.2 MB 1.3 MB/s eta 0:00:22
   - -------------------------------------- 0.8/28.2 MB 1.2 MB/s eta 0:00:23
   - -------------------------------------- 1.0/28.2 MB 1.2 MB/s eta 0:00:22
   - -------------------------------------- 1.3/28.2 MB 1.2 MB/s eta 0:00:22
   -- ------------------------------------- 1.6/28.2 MB 1.2 MB/s eta 0:00:22
   -- ------------------------------------- 2.1/28.2 MB 1.3 MB/s eta 0:00:21
   -- ------------------------------------- 2.1/28.2 MB 1.3 MB/s eta 0:00:21
   -- ------------------------------------- 2.1/28.2 MB 1.3 MB/s eta 0:00:21
   --- ------------------------------------ 2.4/28.2 MB 1.1 MB/s eta 0:00:24
   --- ------------------------------------ 2.4/28.2 MB 1.1 MB/s eta 0:00:24
   --- ------------------------------------ 2.6/28.2 MB 1.0 MB/s eta 0:00:25
   ---- ----------------------------------- 2.9/28.2 MB 1.0 MB/s eta 0:00:26
   ---- ----------------------------------- 3.1/28.2 MB 1.0 MB/s eta 0:00:25
   ---- ----------------------------------- 3.1/28.2 MB 1.0 MB/s eta 0:00:25
   ---- ----------------------------------- 3.4/28.2 MB 982.5 kB/s eta 0:00:26
   ---- ----------------------------------- 3.4/28.2 MB 982.5 kB/s eta 0:00:26
   ---- ----------------------------------- 3.4/28.2 MB 982.5 kB/s eta 0:00:26
   ----- ---------------------------------- 3.7/28.2 MB 894.1 kB/s eta 0:00:28
   ----- ---------------------------------- 3.9/28.2 MB 893.0 kB/s eta 0:00:28
   ----- ---------------------------------- 4.2/28.2 MB 921.0 kB/s eta 0:00:27
   ------ --------------------------------- 4.5/28.2 MB 920.4 kB/s eta 0:00:26
   ------ --------------------------------- 4.5/28.2 MB 920.4 kB/s eta 0:00:26
   ------ --------------------------------- 4.7/28.2 MB 929.2 kB/s eta 0:00:26
   ------- -------------------------------- 5.0/28.2 MB 929.7 kB/s eta 0:00:26
   ------- -------------------------------- 5.5/28.2 MB 965.5 kB/s eta 0:00:24
   -------- ------------------------------- 5.8/28.2 MB 985.4 kB/s eta 0:00:23
   -------- ------------------------------- 6.3/28.2 MB 1.0 MB/s eta 0:00:22
   --------- ------------------------------ 6.8/28.2 MB 1.1 MB/s eta 0:00:20
   ---------- ----------------------------- 7.1/28.2 MB 1.1 MB/s eta 0:00:20
   ---------- ----------------------------- 7.3/28.2 MB 1.1 MB/s eta 0:00:19
   ---------- ----------------------------- 7.6/28.2 MB 1.1 MB/s eta 0:00:19
   ----------- ---------------------------- 7.9/28.2 MB 1.1 MB/s eta 0:00:19
   ----------- ---------------------------- 7.9/28.2 MB 1.1 MB/s eta 0:00:19
   ----------- ---------------------------- 8.1/28.2 MB 1.1 MB/s eta 0:00:19
   ----------- ---------------------------- 8.4/28.2 MB 1.1 MB/s eta 0:00:19
   ------------ --------------------------- 8.7/28.2 MB 1.1 MB/s eta 0:00:18
   ------------ --------------------------- 8.9/28.2 MB 1.1 MB/s eta 0:00:18
   ------------ --------------------------- 9.2/28.2 MB 1.1 MB/s eta 0:00:18
   ------------ --------------------------- 9.2/28.2 MB 1.1 MB/s eta 0:00:18
   ------------- -------------------------- 9.7/28.2 MB 1.1 MB/s eta 0:00:17
   -------------- ------------------------- 10.0/28.2 MB 1.1 MB/s eta 0:00:17
   -------------- ------------------------- 10.5/28.2 MB 1.1 MB/s eta 0:00:16
   --------------- ------------------------ 10.7/28.2 MB 1.1 MB/s eta 0:00:16
   --------------- ------------------------ 11.3/28.2 MB 1.2 MB/s eta 0:00:15
   ---------------- ----------------------- 11.5/28.2 MB 1.2 MB/s eta 0:00:15
   ----------------- ---------------------- 12.1/28.2 MB 1.2 MB/s eta 0:00:14
   ----------------- ---------------------- 12.3/28.2 MB 1.2 MB/s eta 0:00:14
   ------------------ --------------------- 12.8/28.2 MB 1.2 MB/s eta 0:00:13
   ------------------ --------------------- 13.4/28.2 MB 1.3 MB/s eta 0:00:12
   ------------------- -------------------- 13.6/28.2 MB 1.3 MB/s eta 0:00:12
   -------------------- ------------------- 14.2/28.2 MB 1.3 MB/s eta 0:00:11
   -------------------- ------------------- 14.7/28.2 MB 1.3 MB/s eta 0:00:11
   --------------------- ------------------ 14.9/28.2 MB 1.3 MB/s eta 0:00:11
   --------------------- ------------------ 15.5/28.2 MB 1.3 MB/s eta 0:00:10
   ---------------------- ----------------- 15.7/28.2 MB 1.3 MB/s eta 0:00:10
   ----------------------- ---------------- 16.3/28.2 MB 1.3 MB/s eta 0:00:09
   ----------------------- ---------------- 16.5/28.2 MB 1.3 MB/s eta 0:00:09
   ----------------------- ---------------- 16.8/28.2 MB 1.3 MB/s eta 0:00:09
   ------------------------ --------------- 17.3/28.2 MB 1.4 MB/s eta 0:00:09
   ------------------------- -------------- 18.1/28.2 MB 1.4 MB/s eta 0:00:08
   -------------------------- ------------- 18.6/28.2 MB 1.4 MB/s eta 0:00:07
   --------------------------- ------------ 19.1/28.2 MB 1.4 MB/s eta 0:00:07
   --------------------------- ------------ 19.7/28.2 MB 1.5 MB/s eta 0:00:06
   ---------------------------- ----------- 20.2/28.2 MB 1.5 MB/s eta 0:00:06
   ----------------------------- ---------- 20.7/28.2 MB 1.5 MB/s eta 0:00:06
   ------------------------------ --------- 21.5/28.2 MB 1.5 MB/s eta 0:00:05
   ------------------------------- -------- 22.0/28.2 MB 1.5 MB/s eta 0:00:05
   -------------------------------- ------- 22.8/28.2 MB 1.6 MB/s eta 0:00:04
   -------------------------------- ------- 22.8/28.2 MB 1.6 MB/s eta 0:00:04
   --------------------------------- ------ 23.3/28.2 MB 1.6 MB/s eta 0:00:04
   --------------------------------- ------ 23.9/28.2 MB 1.6 MB/s eta 0:00:03
   ---------------------------------- ----- 24.1/28.2 MB 1.6 MB/s eta 0:00:03
   ---------------------------------- ----- 24.4/28.2 MB 1.6 MB/s eta 0:00:03
   ---------------------------------- ----- 24.6/28.2 MB 1.6 MB/s eta 0:00:03
   ----------------------------------- ---- 24.9/28.2 MB 1.6 MB/s eta 0:00:03
   ----------------------------------- ---- 25.2/28.2 MB 1.6 MB/s eta 0:00:02
   ------------------------------------ --- 25.4/28.2 MB 1.6 MB/s eta 0:00:02
   ------------------------------------ --- 26.0/28.2 MB 1.6 MB/s eta 0:00:02
   ------------------------------------- -- 26.2/28.2 MB 1.6 MB/s eta 0:00:02
   ------------------------------------- -- 26.5/28.2 MB 1.6 MB/s eta 0:00:02
   ------------------------------------- -- 26.7/28.2 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 27.0/28.2 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 27.3/28.2 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 27.5/28.2 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  27.8/28.2 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------  28.0/28.2 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 28.2/28.2 MB 1.5 MB/s  0:00:18
Using cached pyyaml-6.0.3-cp314-cp314-win_amd64.whl (156 kB)
Using cached requests-2.33.1-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl (159 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached anyio-4.13.0-py3-none-any.whl (114 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached typer-0.24.1-py3-none-any.whl (56 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached click-8.3.2-py3-none-any.whl (108 kB)
Using cached rich-14.3.3-py3-none-any.whl (310 kB)
Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)
Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Pham Quoc Viet\\AppData\\Roaming\\Python\\Python314\\site-packages\\pygments\\lexers\\slash.py'
Check the permissions.


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Collecting datasets
  Using cached datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Collecting filelock (from datasets)
  Using cached filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting numpy>=1.17 (from datasets)
  Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting pyarrow>=21.0.0 (from datasets)
  Using cached pyarrow-23.0.1-cp314-cp314-win_amd64.whl.metadata (3.1 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets)
  Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting requests>=2.32.2 (from datasets)
  Using cached requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting httpx<1.0.0 (from datasets)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting tqdm>=4.66.3 (from datasets)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting xxhash (from datasets)
  Using cached xxhash-3.6.0-cp314-cp314-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Using cached multiprocess-0.70.19-py314-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2026.2.0,>=2023.1.0 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<2.0,>=0.25.0 (from datasets)
  Using cached huggingface_hub-1.9.1-py3-none-any.whl.metadata (14 kB)
Collecting packaging (from datasets)
  Using cached packaging-26.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pyyaml>=5.1 (from datasets)
  Using cached pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohttp-3.13.5-cp314-cp314-win_amd64.whl.metadata (8.4 kB)
Collecting anyio (from httpx<1.0.0->datasets)
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting certifi (from httpx<1.0.0->datasets)
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1.0.0->datasets)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1.0.0->datasets)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0->datasets)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached hf_xet-1.4.3-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting typer (from huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting typing-extensions>=4.1.0 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached frozenlist-1.8.0-cp314-cp314-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached multidict-6.7.1-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached propcache-0.4.1-cp314-cp314-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached yarl-1.23.0-cp314-cp314-win_amd64.whl.metadata (82 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.32.2->datasets)
  Using cached charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.32.2->datasets)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting colorama (from tqdm>=4.66.3->datasets)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting python-dateutil>=2.8.2 (from pandas->datasets)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting tzdata (from pandas->datasets)
  Using cached tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->datasets)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting click>=8.2.1 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached click-8.3.2-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached datasets-4.8.4-py3-none-any.whl (526 kB)
Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Using cached fsspec-2026.2.0-py3-none-any.whl (202 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached huggingface_hub-1.9.1-py3-none-any.whl (637 kB)
Using cached hf_xet-1.4.3-cp37-abi3-win_amd64.whl (3.7 MB)
Using cached multiprocess-0.70.19-py314-none-any.whl (160 kB)
Using cached aiohttp-3.13.5-cp314-cp314-win_amd64.whl (464 kB)
Using cached multidict-6.7.1-cp314-cp314-win_amd64.whl (45 kB)
Using cached yarl-1.23.0-cp314-cp314-win_amd64.whl (89 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached filelock-3.25.2-py3-none-any.whl (26 kB)
Using cached frozenlist-1.8.0-cp314-cp314-win_amd64.whl (44 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.4 MB 4.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.4 MB 4.7 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.4 MB 5.1 MB/s eta 0:00:02
   --------------- ------------------------ 4.7/12.4 MB 5.2 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.4 MB 5.1 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.4 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.4 MB 5.2 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.4 MB 5.3 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.4 MB 5.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.4 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 5.1 MB/s  0:00:02
Downloading packaging-26.0-py3-none-any.whl (74 kB)
Downloading propcache-0.4.1-cp314-cp314-win_amd64.whl (41 kB)
Downloading pyarrow-23.0.1-cp314-cp314-win_amd64.whl (28.2 MB)
   ---------------------------------------- 0.0/28.2 MB ? eta -:--:--
   - -------------------------------------- 1.0/28.2 MB 4.8 MB/s eta 0:00:06
   --- ------------------------------------ 2.4/28.2 MB 5.8 MB/s eta 0:00:05
   ---- ----------------------------------- 3.4/28.2 MB 5.5 MB/s eta 0:00:05
   ------ --------------------------------- 4.7/28.2 MB 5.6 MB/s eta 0:00:05
   -------- ------------------------------- 5.8/28.2 MB 5.5 MB/s eta 0:00:05
   --------- ------------------------------ 6.8/28.2 MB 5.5 MB/s eta 0:00:04
   ---------- ----------------------------- 7.6/28.2 MB 5.2 MB/s eta 0:00:04
   ----------- ---------------------------- 8.4/28.2 MB 5.0 MB/s eta 0:00:04
   ------------- -------------------------- 9.4/28.2 MB 4.9 MB/s eta 0:00:04
   --------------- ------------------------ 11.0/28.2 MB 5.2 MB/s eta 0:00:04
   ----------------- ---------------------- 12.3/28.2 MB 5.2 MB/s eta 0:00:04
   ------------------ --------------------- 12.8/28.2 MB 5.1 MB/s eta 0:00:04
   ------------------ --------------------- 13.1/28.2 MB 4.8 MB/s eta 0:00:04
   ------------------- -------------------- 13.9/28.2 MB 4.6 MB/s eta 0:00:04
   -------------------- ------------------- 14.2/28.2 MB 4.4 MB/s eta 0:00:04
   --------------------- ------------------ 14.9/28.2 MB 4.3 MB/s eta 0:00:04
   ---------------------- ----------------- 16.0/28.2 MB 4.4 MB/s eta 0:00:03
   ----------------------- ---------------- 16.8/28.2 MB 4.3 MB/s eta 0:00:03
   ------------------------ --------------- 17.6/28.2 MB 4.3 MB/s eta 0:00:03
   -------------------------- ------------- 18.6/28.2 MB 4.3 MB/s eta 0:00:03
   --------------------------- ------------ 19.4/28.2 MB 4.3 MB/s eta 0:00:03
   ---------------------------- ----------- 20.2/28.2 MB 4.3 MB/s eta 0:00:02
   ------------------------------ --------- 21.2/28.2 MB 4.3 MB/s eta 0:00:02
   ------------------------------ --------- 21.8/28.2 MB 4.2 MB/s eta 0:00:02
   ------------------------------- -------- 22.0/28.2 MB 4.1 MB/s eta 0:00:02
   ------------------------------- -------- 22.3/28.2 MB 4.1 MB/s eta 0:00:02
   -------------------------------- ------- 22.8/28.2 MB 4.0 MB/s eta 0:00:02
   --------------------------------- ------ 23.3/28.2 MB 4.0 MB/s eta 0:00:02
   ---------------------------------- ----- 24.1/28.2 MB 3.9 MB/s eta 0:00:02
   ---------------------------------- ----- 24.4/28.2 MB 3.9 MB/s eta 0:00:01
   ----------------------------------- ---- 24.9/28.2 MB 3.8 MB/s eta 0:00:01
   ------------------------------------ --- 25.4/28.2 MB 3.8 MB/s eta 0:00:01
   ------------------------------------ --- 25.4/28.2 MB 3.8 MB/s eta 0:00:01
   ------------------------------------ --- 26.0/28.2 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 26.7/28.2 MB 3.6 MB/s eta 0:00:01
   -------------------------------------- - 27.5/28.2 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 28.2/28.2 MB 3.6 MB/s  0:00:07
Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl (156 kB)
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl (159 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading anyio-4.13.0-py3-none-any.whl (114 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 5.6 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/9.9 MB 4.9 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.9 MB 5.3 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.9 MB 5.7 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.9 MB 5.7 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.9 MB 5.4 MB/s eta 0:00:01
   ----------------------------- ---------- 7.3/9.9 MB 5.1 MB/s eta 0:00:01
   ------------------------------- -------- 7.9/9.9 MB 4.9 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 4.6 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 4.3 MB/s  0:00:02
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Downloading typer-0.24.1-py3-none-any.whl (56 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading click-8.3.2-py3-none-any.whl (108 kB)
Downloading rich-14.3.3-py3-none-any.whl (310 kB)
Downloading pygments-2.20.0-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ----------------- ---------------------- 0.5/1.2 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 2.9 MB/s  0:00:00
Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Downloading xxhash-3.6.0-cp314-cp314-win_amd64.whl (32 kB)
Installing collected packages: xxhash, urllib3, tzdata, typing-extensions, six, shellingham, pyyaml, pygments, pyarrow, propcache, packaging, numpy, multidict, mdurl, idna, hf-xet, h11, fsspec, frozenlist, filelock, dill, colorama, charset_normalizer, certifi, attrs, annotated-doc, aiohappyeyeballs, yarl, tqdm, requests, python-dateutil, multiprocess, markdown-it-py, httpcore, click, anyio, aiosignal, rich, pandas, httpx, aiohttp, typer, huggingface-hub, datasets

    ---------------------------------------  1/44 [urllib3]
    ---------------------------------------  1/44 [urllib3]
    ---------------------------------------  1/44 [urllib3]
    ---------------------------------------  1/44 [urllib3]
    ---------------------------------------  1/44 [urllib3]
    ---------------------------------------  1/44 [urllib3]
    ---------------------------------------  1/44 [urllib3]
    ---------------------------------------  1/44 [urllib3]
    ---------------------------------------  1/44 [urllib3]
   - --------------------------------------  2/44 [tzdata]
   - --------------------------------------  2/44 [tzdata]
   --- ------------------------------------  4/44 [six]
   ---- -----------------------------------  5/44 [shellingham]
   ----- ----------------------------------  6/44 [pyyaml]
   ----- ----------------------------------  6/44 [pyyaml]
   ----- ----------------------------------  6/44 [pyyaml]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------ ---------------------------------  7/44 [pygments]
   ------- --------------------------------  8/44 [pyarrow]
   ------- --------------------------------  8/44 [pyarrow]
   ------- --------------------------------  8/44 [pyarrow]
   ------- --------------------------------  8/44 [pyarrow]
   ------- --------------------------------  8/44 [pyarrow]
   ------- --------------------------------  8/44 [pyarrow]
   ------- --------------------------------  8/44 [pyarrow]

  WARNING: The script pygmentize.exe is installed in 'C:\Users\Pham Quoc Viet\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\Pham Quoc Viet\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer.exe is installed in 'C:\Users\Pham Quoc Viet\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm.exe is installed in 'C:\Users\Pham Quoc Viet\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown-it.exe is installed in 'C:\Users\Pham Quoc Viet\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script httpx.exe is installed in 'C:\Users\Pham Quoc Viet\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script typer.exe is installed in 'C:\Users\Pham Quoc Viet\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts hf.exe and tiny-agents.exe are installed in 'C:\Users\Pham Quoc Viet\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script datasets-cli.exe is installed in 'C:\Users\Pham Quoc Viet\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

In [1]:
from datasets import load_dataset
emotion_dataset = load_dataset("emotion")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
(emotion_dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
})

In [8]:
train_df = emotion_dataset['train'].to_pandas()

In [9]:
train_df.head()

                                                text  label
0                            i didnt feel humiliated      0
1  i can go from feeling so hopeless to so damned...      0
2   im grabbing a minute to post i feel greedy wrong      3
3  i am ever feeling nostalgic about the fireplac...      2
4                               i am feeling grouchy      3

In [10]:
validation_df = emotion_dataset['validation'].to_pandas()
test_df = emotion_dataset['test'].to_pandas()

In [17]:
label_text = emotion_dataset['train'].features['label'].names
label_text

['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

In [19]:
features = emotion_dataset['train'].features

int2str() method <span style="color:green">**converts an interger ID to its corresponding string label**

In [30]:
for i in range(len(label_text)):
    print(f"i={i}, label={label_text[i]} compared to features={features['label'].int2str(i)}")

i=0, label=sadness compared to features=sadness
i=1, label=joy compared to features=joy
i=2, label=love compared to features=love
i=3, label=anger compared to features=anger
i=4, label=fear compared to features=fear
i=5, label=surprise compared to features=surprise

In [32]:
label_map = {i: features['label'].int2str(i) for i in range(len(label_text))}
label_map

{0: 'sadness', 1: 'joy', 2: 'love', 3: 'anger', 4: 'fear', 5: 'surprise'}

In [40]:
label2id = {v: k for k, v in label_map.items()}
label2id

{'sadness': 0, 'joy': 1, 'love': 2, 'anger': 3, 'fear': 4, 'surprise': 5}

In [35]:
train_df['label_encoded'] = train_df['label'].map(label_map)
train_df.head()

                                                text  label label_encoded
0                            i didnt feel humiliated      0       sadness
1  i can go from feeling so hopeless to so damned...      0       sadness
2   im grabbing a minute to post i feel greedy wrong      3         anger
3  i am ever feeling nostalgic about the fireplac...      2          love
4                               i am feeling grouchy      3         anger

In [42]:
train_df['label'].value_counts(normalize=True).sort_index()

label
0    0.291625
1    0.335125
2    0.081500
3    0.134937
4    0.121063
5    0.035750
Name: proportion, dtype: float64